### ISSUE TITLE
Fix the icons for Spring Cloud Auto-Config

### ISSUE THREAD

**Issue by bczoma** [SolaceSamples/solace-samples-cloudfoundry-java#34]
For Java, JMS and JNDI.

**Comment by alyrasmy** [comment]
This issue can be fixed by setting the icon dimensions in the tutorial file. 
Note: first you have to pull in the latest template for this to work.

e.g. docs/_tutorials/java-app.md

layout: tutorials
title: Java Application
summary: A Java Application showing how to consume the VCAP_SERVICES environment variable.
icon: I_java.svg
icon-height: 90px
icon-width: 72px

**Comment by bczoma** [comment]
Thanks Aly. We also concluded with Mark that new icons are needed, I'm waiting for that.

**Comment by bczoma** [comment]
This has been addressed some time ago, closing.
